baseURL = "https://grif-usherbrooke.github.io"
theme = "terminal"
defaultContentLanguageInSubdir = true
defaultContentLanguage = "en"
title = "GRIF"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en"
    title = "Research group on fundamental computer science of the Université de Sherbrooke"
    weight = 1

    [languages.en.params]
      dateFormat = "2006-01-02"
      subtitle = "The GRIF is the fundamental computer science research group at the Université de Sherbrooke."
      keywords = "theoretical computer science, algorithms, bioinformatics, formal methods, cybersecurity, automata theory, quantum computing, Université de Sherbrooke, Quebec, Canada, GRIF"
  
    [languages.en.params.logo]
      logoText = "GRIF @ UdeS"
      logoHomeLink = "/"

    [[languages.en.menu.main]]
     name = "Members"
     url = "#members"
     weight = 1

    [[languages.en.menu.main]]
      name = "Research areas"
      url = "#themes"
      weight = 2

    [[languages.en.menu.main]]
      name = "Courses"
      url = "#courses"
      weight = 3

    [[languages.en.menu.main]]
      name = "Talks"
      url = "#talks"
      weight = 4
	
  [languages.fr]
    languageName = "Français"
    languageCode = "fr"
    title = "GRIF – Groupe de recherche en informatique fondamentale de l'Université de Sherbrooke"
    weight = 2

    [languages.fr.params]
      dateFormat = "02/01/2006"
      subtitle = "Le GRIF est le groupe de recherche en informatique fondamentale de l'Université de Sherbrooke."
      keywords = "informatique théorique, informatique fondamentale, algorithmique, bio-informatique, méthodes formelles, cybersécurité, automates, informatique quantique, Université de Sherbrooke, Québec, Canada, GRIF"

    [languages.fr.params.logo]
      logoText = "GRIF @ UdeS"
      logoHomeLink = "/"

    [[languages.fr.menu.main]]
     name = "Membres"
     url = "#members"
     weight = 1

    [[languages.fr.menu.main]]
      name = "Axes de recherche"
      url = "#themes"
      weight = 2

    [[languages.fr.menu.main]]
      name = "Cours"
      url = "#courses"
      weight = 3

    [[languages.fr.menu.main]]
      name = "Présentations"
      url = "#talks"
      weight = 4

[params]
  showLanguageSelector = true
  Toc = true
  fullWidthTheme = false
  centerTheme = false
